let express = require('express');
let pug = require('pug');
let babel = require('jade-babel');
let bodyParser = require('body-parser');

let form = require('formidable');

let app = express();
let router = express.Router();
app.set('view engine', 'pug')
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended:true}));

let deviceList = [
    {
        name:"喀什",
        date:"2017-05-18",
        errorNumber:0,
        offlineNumber:0,
        children: [
            {
                name:"阳光小区 （1861人）",
                date:"2017-05-18",
                errorNumber:0,
                offlineNumber:0,
                children: [
                    {
                        name:"喀什阳光1路设备",
                        id:"1",
                        brand:"-",
                        ip:"192.168.104.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"2",
                                brand:"Hikvision",
                                ip:"rtsp://admin:admin12345@10.141.5.141:554/mpeg4",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",
                                nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"2",
                                brand:"Hikvision",
                                ip:"rtsp://admin:admin12345@10.141.5.142:554/mpeg4",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",
                                nocheck:true
                            }
                        ]
                    },
                    {
                        name:"2路设备",
                        id:"4",
                        brand:"-",
                        ip:"192.168.1.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"5",
                                brand:"Hikvision",
                                ip:"192.168.14.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",
                                nocheck:true
                            },
                            {
                                name: "Camera02",
                                id: "6",
                                brand: "Hikvision",
                                ip: "192.168.14.139",
                                port: "554",
                                username: "admin",
                                password: "admin12345",
                                stream: "cam,realmonitor?channel=1subtype",
                                timeout: "300",
                                state: "空闲",
                                nocheck: true
                            }
                        ]
                    },
                    {
                        name:"3路设备",
                        id:"7",
                        brand:"-",
                        ip:"192.168.13.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"8",
                                brand:"Hikvision",
                                ip:"192.168.13.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"9",
                                brand:"DH",
                                ip:"192.168.13.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera03",
                                id:"10",
                                brand:"DH",
                                ip:"192.168.13.189",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    }
                ]
            },
            {
                name:"惠民小区 （133人）",
                date:"2017-05-18",
                errorNumber:0,
                offlineNumber:0,
                children: [
                    {
                        name:"喀什惠民1路设备",
                        id:"1",
                        brand:"-",
                        ip:"192.168.104.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"2路设备",
                        id:"4",
                        brand:"-",
                        ip:"192.168.1.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"5",
                                brand:"Hikvision",
                                ip:"192.168.14.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"6",
                                brand:"Hikvision",
                                ip:"192.168.14.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"3路设备",
                        id:"7",
                        brand:"-",
                        ip:"192.168.13.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"8",
                                brand:"Hikvision",
                                ip:"192.168.13.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"9",
                                brand:"DH",
                                ip:"192.168.13.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera03",
                                id:"10",
                                brand:"DH",
                                ip:"192.168.13.189",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    }
                ]
            }
        ]},
    {
        name:"乌鲁木齐",
        date:"2017-05-18",
        errorNumber:2,
        offlineNumber:2,
        children: [
            {
                name:"乌鲁木齐小区 （1861人）",
                date:"2017-05-18",
                errorNumber:2,
                offlineNumber:1,
                children: [
                    {
                        name:"乌鲁木齐1路设备",
                        id:"1",
                        brand:"-",
                        ip:"192.168.104.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"2路设备",
                        id:"4",
                        brand:"-",
                        ip:"192.168.1.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"5",
                                brand:"Hikvision",
                                ip:"192.168.14.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"6",
                                brand:"Hikvision",
                                ip:"192.168.14.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"3路设备",
                        id:"7",
                        brand:"-",
                        ip:"192.168.13.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"8",
                                brand:"Hikvision",
                                ip:"192.168.13.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"9",
                                brand:"DH",
                                ip:"192.168.13.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera03",
                                id:"10",
                                brand:"DH",
                                ip:"192.168.13.189",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    }
                ]
            },
            {
                name:"万科小区 （133人）",
                date:"2017-05-18",
                errorNumber:0,
                offlineNumber:1,
                children: [
                    {
                        name:"乌鲁木齐万科1路设备",
                        id:"1",
                        brand:"-",
                        ip:"192.168.104.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"2路设备",
                        id:"4",
                        brand:"-",
                        ip:"192.168.1.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"5",
                                brand:"Hikvision",
                                ip:"192.168.14.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"6",
                                brand:"Hikvision",
                                ip:"192.168.14.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"3路设备",
                        id:"7",
                        brand:"-",
                        ip:"192.168.13.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"8",
                                brand:"Hikvision",
                                ip:"192.168.13.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"9",
                                brand:"DH",
                                ip:"192.168.13.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera03",
                                id:"10",
                                brand:"DH",
                                ip:"192.168.13.189",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    }
                ]
            }
        ]},
    {
        name:"莎车",
        date:"2017-05-18",
        errorNumber:3,
        offlineNumber:1,
        children: [
            {
                name:"莎车阳光小区 （1861人）",
                date:"2017-05-18",
                errorNumber:1,
                offlineNumber:0,
                children: [
                    {
                        name:"莎车阳光1路设备",
                        id:"1",
                        brand:"-",
                        ip:"192.168.104.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"2路设备",
                        id:"4",
                        brand:"-",
                        ip:"192.168.1.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"5",
                                brand:"Hikvision",
                                ip:"192.168.14.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"6",
                                brand:"Hikvision",
                                ip:"192.168.14.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"3路设备",
                        id:"7",
                        brand:"-",
                        ip:"192.168.13.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"8",
                                brand:"Hikvision",
                                ip:"192.168.13.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"9",
                                brand:"DH",
                                ip:"192.168.13.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera03",
                                id:"10",
                                brand:"DH",
                                ip:"192.168.13.189",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    }
                ]
            },
            {
                name:"碧桂园小区 （133人）",
                date:"2017-05-18",
                errorNumber:2,
                offlineNumber:1,
                children: [
                    {
                        name:"莎车碧桂园1路设备",
                        id:"1",
                        brand:"-",
                        ip:"192.168.104.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"2",
                                brand:"Hikvision",
                                ip:"192.168.104.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"2路设备",
                        id:"4",
                        brand:"-",
                        ip:"192.168.1.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"5",
                                brand:"Hikvision",
                                ip:"192.168.14.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"6",
                                brand:"Hikvision",
                                ip:"192.168.14.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",nocheck:true
                            }
                        ]
                    },
                    {
                        name:"3路设备",
                        id:"7",
                        brand:"-",
                        ip:"192.168.13.138",
                        port:"-",
                        username:"admin",
                        password:"admin12345",
                        stream:"-",
                        timeout:"-",
                        state:"空闲",
                        showChildren:false,
                        children:[
                            {
                                name:"Camera01",
                                id:"8",
                                brand:"Hikvision",
                                ip:"192.168.13.138",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",
                                nocheck:true
                            },
                            {
                                name:"Camera02",
                                id:"9",
                                brand:"DH",
                                ip:"192.168.13.139",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",
                                nocheck:true
                            },
                            {
                                name:"Camera03",
                                id:"10",
                                brand:"DH",
                                ip:"192.168.13.189",
                                port:"554",
                                username:"admin",
                                password:"admin12345",
                                stream:"cam,realmonitor?channel=1subtype",
                                timeout:"300",
                                state:"空闲",
                                nocheck:true
                            }
                        ]
                    }
                ]
            }
        ]}
];
let hitRecords = [
    {
        id:1,
        user:{
            name:"爱立托木买买提题雨哦木老爱丽木么么哒",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:2,
        user:{
            name:"爱立托木买买",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:3,
        user:{
            name:"ai12",
            label:"黑名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:4,
        user:{
            name:"爱立12哒",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:5,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:6,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:7,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:8,
        user:{
            name:"艾立托木买买提",
            label:"黑名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:9,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },{
        id:10,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },{
        id:11,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },{
        id:12,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },{
        id:13,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },{
        id:14,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:15,
        user:{
            name:"艾立托木买买提",
            label:"黑名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },{
        id:16,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },{
        id:17,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:18,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:19,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:20,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:21,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:22,
        user:{
            name:"艾立托木买买提",
            label:"黑名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:23,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },{
        id:24,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },{
        id:25,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    },
    {
        id:26,
        user:{
            name:"艾立托木买买提",
            label:"白名单",
            passportNumber:"210120196302073592",
        },
        createTime:"2017-01-20 13:23",
        place:"乌鲁木齐-阳光小区-设备12-Camera01"
    }

];

pug.filters.babel= babel({});
//const index = pug.compileFile('index.pug');

app.use(express.static('public'));
app.get('/pug', function (req, res) {
    res.render('index', { name: 'Hey'})
})
app.get('/get_device_list',function (req,res) {
    res.json(deviceList);
    res.end();
});
app.get('/get_hit_list',function (req,res) {
    let n = req.param('n');
    res.json(hitRecords);
});
app.listen(3000);